### ISSUE TITLE
remove dependency on `is-promise`

### ISSUE THREAD

**Issue by monken** [SBoudrias/run-async#29]
`is-promise` is broken at the moment and since it's just a single line of code, we would be better off including the line in the code of `run-async` instead of relying on a broken dependency.

See https://github.com/then/is-promise/issues/13.

**Comment by mberaz** [comment]
its breaking the build  in Node V12
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\User\Documents\Visual Studio Code\OmniReaderUI\node_modules\is-promise\index.js
require() of ES modules is not supported.
require() of C:\Users\User\Documents\Visual Studio Code\OmniReaderUI\node_modules\is-promise\index.js from C:\Users\User\Documents\Visual Studio Code\OmniReaderUI\node_modules\run-async\index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename C:\Users\User\Documents\Visual Studio Code\OmniReaderUI\node_modules\is-promise\index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\User\Documents\Visual Studio Code\OmniReaderUI\node_modules\is-promise\package.json.

**Comment by Baralabite** [comment]
The issue is with index.js:3, which uses `require('is-promise');`. This should be changed to use import to abide by the latest ES module system.

Let me know how I can assist. This is currently blocking my work.

**Comment by SBoudrias** [comment]
Happy to merge a PR removing the module in favor of inline code.
