### ISSUE TITLE
Promise interface

### ISSUE THREAD

**Issue by SBoudrias** [SBoudrias/run-async#3]
Add the capacity to return a promise from a run-async wrapped function.

**Comment by jamestalmage** [comment]
:+1:

**Comment by jamestalmage** [comment]
This may necessitate switching to node style callbacks (`callback(err, result)`).

Otherwise you are left without a way to handle promise rejection.

Related #4

**Comment by SBoudrias** [comment]
Yes, I think that totally make sense. We should handle error cases.
